import { Injectable, Inject } from '@nestjs/common';
import { DB_CONNECTION } from '../db/database.module';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import * as schema from '../db/schema';
import * as Papa from 'papaparse';
import { BulkUploadResultDto, CsvProductRow } from './dto/bulk-upload.dto';
import { eq, and, sql } from 'drizzle-orm';

@Injectable()
export class ProductBulkService {
  constructor(
    @Inject(DB_CONNECTION)
    private db: NodePgDatabase<typeof schema>,
  ) {}

  /**
   * Generate EAN-13 compatible SKU
   * Format: 99YYMMDDSSSSS
   * - 99: Internal products prefix
   * - YYMMDD: Date (e.g., 260129 for Jan 29, 2026)
   * - SSSSS: 5-digit sequence (padded with zeros)
   */
  private async generateSKU(): Promise<string> {
    // Get next sequence number atomically
    const result = await this.db.execute(
      sql`SELECT get_next_sku_sequence() as seq`,
    );
    const sequence = result.rows[0].seq as number;

    // Format date as YYMMDD
    const now = new Date();
    const yy = now.getFullYear().toString().slice(-2);
    const mm = (now.getMonth() + 1).toString().padStart(2, '0');
    const dd = now.getDate().toString().padStart(2, '0');

    // Format sequence as 5 digits
    const seqStr = sequence.toString().padStart(5, '0');

    return `99${yy}${mm}${dd}${seqStr}`;
  }

  /**
   * Sanitize CSV input to prevent formula injection
   * Strips leading =, +, -, @ characters
   */
  private sanitizeInput(value: string): string {
    if (!value || typeof value !== 'string') return value;
    return value.trim().replace(/^[=+\-@]/, '');
  }

  /**
   * Parse and import CSV file with products
   */
  /**
   * Get or create category by name
   */
  private async getOrCreateCategory(
    tenantId: string,
    categoryName: string,
  ): Promise<string | null> {
    const name = this.sanitizeInput(categoryName);
    if (!name) return null;

    // Check if exists
    const existing = await this.db
      .select()
      .from(schema.categories)
      .where(
        and(
          eq(schema.categories.tenantId, tenantId),
          eq(schema.categories.name, name),
        ),
      )
      .limit(1);

    if (existing.length > 0) {
      return existing[0].id;
    }

    // Create new
    const [newCategory] = await this.db
      .insert(schema.categories)
      .values({
        tenantId,
        name,
      })
      .returning({ id: schema.categories.id });

    return newCategory.id;
  }

  /**
   * Parse and import CSV file with products
   */
  async bulkImport(
    csvBuffer: Buffer,
    tenantId: string,
  ): Promise<BulkUploadResultDto> {
    const result: BulkUploadResultDto = {
      success: 0,
      skipped: 0,
      errors: 0,
      autoGeneratedSkus: 0,
      details: {
        skippedItems: [],
        errorItems: [],
        autoSkus: [],
      },
    };

    // Parse CSV
    const csvString = csvBuffer.toString('utf-8');
    const parsed = Papa.parse<Record<string, string>>(csvString, {
      header: true,
      skipEmptyLines: true,
      transformHeader: (header) => header.trim(),
    });

    if (parsed.errors.length > 0) {
      throw new Error(
        `CSV parsing failed: ${parsed.errors.map((e) => e.message).join(', ')}`,
      );
    }

    // Cache categories to avoid repeated DB calls in the same request
    const categoryCache = new Map<string, string>();

    // Process each row
    for (let i = 0; i < parsed.data.length; i++) {
      const row = parsed.data[i];
      const rowNumber = i + 2;

      try {
        const name = this.sanitizeInput(row['Product Name'] || row['name']);
        if (!name) {
          result.errors++;
          result.details.errorItems.push({
            row: rowNumber,
            name: '-',
            error: 'Missing product name',
          });
          continue;
        }

        const priceStr = row['MRP'] || row['price'];
        if (!priceStr) {
          result.errors++;
          result.details.errorItems.push({
            row: rowNumber,
            name,
            error: 'Missing price',
          });
          continue;
        }

        const price = Math.round(parseFloat(priceStr) * 100);
        if (isNaN(price) || price <= 0) {
          result.errors++;
          result.details.errorItems.push({
            row: rowNumber,
            name,
            error: 'Invalid price',
          });
          continue;
        }

        // Handle Category
        let categoryId: string | null = null;
        const categoryName = row['Category'] || row['category'];
        if (categoryName) {
          if (categoryCache.has(categoryName)) {
            categoryId = categoryCache.get(categoryName)!;
          } else {
            categoryId = await this.getOrCreateCategory(tenantId, categoryName);
            if (categoryId) {
              categoryCache.set(categoryName, categoryId);
            }
          }
        }

        let sku = this.sanitizeInput(
          row['Barcode/SKU'] || row['sku'] || row['SKU'],
        );
        let isAutoSku = false;

        if (!sku) {
          sku = await this.generateSKU();
          isAutoSku = true;
          result.autoGeneratedSkus++;
          result.details.autoSkus.push({
            name,
            generatedSku: sku,
          });
        }

        const existing = await this.db
          .select()
          .from(schema.products)
          .where(
            and(
              eq(schema.products.tenantId, tenantId),
              eq(schema.products.sku, sku),
            ),
          )
          .limit(1);

        if (existing.length > 0) {
          result.skipped++;
          result.details.skippedItems.push({
            sku,
            name,
            reason: 'Duplicate SKU',
          });
          continue;
        }

        const stock = parseFloat(row['Stock Quantity'] || row['stock'] || '0');
        const wholesalePrice = row['Wholesale Price']
          ? Math.round(parseFloat(row['Wholesale Price']) * 100)
          : null;
        const taxRate = row['Tax rate'] ? parseFloat(row['Tax rate']) : null;

        await this.db.insert(schema.products).values({
          tenantId,
          name,
          sku,
          price,
          stock: stock >= 0 ? stock : 0,
          wholesalePrice,
          taxRate,
          uom: this.sanitizeInput(row['UOM'] || row['uom']),
          reorderPoint: row['Reorder Point']
            ? parseInt(row['Reorder Point'])
            : null,
          safetyStock: row['Safety stock']
            ? parseInt(row['Safety stock'])
            : null,
          supplier: this.sanitizeInput(row['Supplier'] || row['supplier']),
          brand: this.sanitizeInput(row['Brand'] || row['brand']),
          categoryId: categoryId,
          isActive: true,
        });

        result.success++;
      } catch (error) {
        result.errors++;
        result.details.errorItems.push({
          row: rowNumber,
          name: row['Product Name'] || row['name'] || '-',
          error: error.message,
        });
      }
    }

    return result;
  }
}
