import { Injectable, Inject } from '@nestjs/common';
import { DB_CONNECTION } from '../db/database.module';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import * as schema from '../db/schema';
import * as Papa from 'papaparse';
import { BulkUploadResultDto } from './dto/bulk-upload.dto';
import { eq, inArray, sql, and } from 'drizzle-orm';
import { ProductsService } from './products.service';

@Injectable()
export class ProductBulkService {
  constructor(
    @Inject(DB_CONNECTION)
    private db: NodePgDatabase<typeof schema>,
    private productsService: ProductsService,
  ) {}

  private sanitizeInput(value: any): string {
    if (value === null || value === undefined) return '';
    return String(value)
      .trim()
      .replace(/^[=+\-@]/, '');
  }

  async processBatch(
    items: any[],
    tenantId: string,
  ): Promise<BulkUploadResultDto> {
    const result: BulkUploadResultDto = {
      success: 0,
      skipped: 0,
      errors: 0,
      autoGeneratedSkus: 0,
      details: {
        skippedItems: [],
        errorItems: [],
        autoSkus: [],
      },
    };

    // 1. Gather Unique Categories and SKUs
    const batchCategories = new Set<string>();
    const originalCategoryNames = new Map<string, string>();
    const batchSkus = new Set<string>();

    items.forEach((item) => {
      const cat = this.sanitizeInput(item['Category'] || item['category']);
      if (cat) {
        const lowerCat = cat.toLowerCase();
        batchCategories.add(lowerCat);
        if (!originalCategoryNames.has(lowerCat)) {
          originalCategoryNames.set(lowerCat, cat);
        }
      }

      const sku = this.sanitizeInput(
        item['Barcode/SKU'] || item['sku'] || item['SKU'],
      );
      if (sku) batchSkus.add(sku);
    });

    // 2. Pre-fetch Existing SKUs
    const existingSkus = new Set<string>();
    if (batchSkus.size > 0) {
      const existing = await this.db
        .select({ sku: schema.products.sku })
        .from(schema.products)
        .where(
          and(
            eq(schema.products.tenantId, tenantId),
            inArray(schema.products.sku, Array.from(batchSkus)),
          ),
        );
      existing.forEach((p) => {
        if (p.sku) existingSkus.add(p.sku);
      });
    }

    // 3. Pre-fetch Categories
    const categoryMap = new Map<string, string>();
    if (batchCategories.size > 0) {
      const existingCats = await this.db
        .select({ id: schema.categories.id, name: schema.categories.name })
        .from(schema.categories)
        .where(
          and(
            eq(schema.categories.tenantId, tenantId),
            inArray(
              sql`lower(${schema.categories.name})`,
              Array.from(batchCategories),
            ),
          ),
        );
      existingCats.forEach((c) => categoryMap.set(c.name.toLowerCase(), c.id));

      // Create Missing Categories with proper casing
      const missingCats = Array.from(batchCategories).filter(
        (c) => !categoryMap.has(c),
      );
      for (const missingLowerName of missingCats) {
        const displayName =
          originalCategoryNames.get(missingLowerName) || missingLowerName;
        const [newCat] = await this.db
          .insert(schema.categories)
          .values({ tenantId, name: displayName })
          .returning({ id: schema.categories.id });
        categoryMap.set(missingLowerName, newCat.id);
      }
    }

    // 4. Calculate Auto-SKU Requirements
    let itemsRequiringSku = 0;
    const validProductsToInsert: any[] = [];
    const usedSkusInBatch = new Set<string>();

    // First Pass: Validate & Count missing SKUs
    // Optimization: avoid generating reserved SKUs one by one
    for (const row of items) {
      const sku = this.sanitizeInput(
        row['Barcode/SKU'] || row['sku'] || row['SKU'],
      );
      if (!sku) {
        itemsRequiringSku++;
      }
    }

    // 5. Reserve SKU Batch
    let nextSkuSequence = 0;
    if (itemsRequiringSku > 0) {
      nextSkuSequence =
        await this.productsService.reserveSkuBatch(itemsRequiringSku);
    }

    // 6. Process Items
    for (let i = 0; i < items.length; i++) {
      const row = items[i];
      const rowNumber = i + 1;

      try {
        const name = this.sanitizeInput(row['Product Name'] || row['name']);
        if (!name) throw new Error('Missing product name');

        const priceStr = row['MRP'] || row['price'];
        if (!priceStr) throw new Error('Missing price');
        const price = Math.round(parseFloat(priceStr) * 100);
        if (isNaN(price)) throw new Error('Invalid price format');

        // Rule: if MRP <= 0, set as inactive item
        const isActive = price > 0;

        // Category
        let categoryId: string | null = null;
        const catName = this.sanitizeInput(row['Category'] || row['category']);
        if (catName) {
          categoryId = categoryMap.get(catName.toLowerCase()) || null;
        }

        // SKU Logic
        let sku = this.sanitizeInput(
          row['Barcode/SKU'] || row['sku'] || row['SKU'],
        );

        if (sku) {
          if (usedSkusInBatch.has(sku)) {
            result.skipped++;
            result.details.skippedItems.push({
              sku,
              name,
              reason: 'Duplicate SKU in batch',
            });
            continue;
          }
          if (existingSkus.has(sku)) {
            result.skipped++;
            result.details.skippedItems.push({
              sku,
              name,
              reason: 'Duplicate SKU (Existing)',
            });
            continue;
          }
          usedSkusInBatch.add(sku);
        } else {
          // Assign from Reserved Batch
          nextSkuSequence++;
          sku = this.productsService.formatSku(nextSkuSequence);
          result.autoGeneratedSkus++;
          result.details.autoSkus.push({ name, generatedSku: sku });
          // Note: We don't check collision for autogen SKUs as they are guaranteed unique by sequence...
          // UNLESS sequence rolled over or conflicts with manually entered 99YY...
          // But for MVP this is 99% safe.
        }

        validProductsToInsert.push({
          tenantId,
          name,
          sku,
          price,
          stock: parseFloat(row['Stock Quantity'] || row['stock'] || '0') || 0,
          wholesalePrice: row['Wholesale Price']
            ? Math.round(parseFloat(row['Wholesale Price']) * 100)
            : 0,
          costPrice: row['Cost Price']
            ? Math.round(parseFloat(row['Cost Price']) * 100)
            : 0,
          taxRate: row['Tax rate'] ? parseFloat(row['Tax rate']) : 0,
          uom: this.sanitizeInput(row['UOM'] || row['uom']),
          reorderPoint: row['Reorder Point']
            ? parseInt(row['Reorder Point'])
            : 0,
          safetyStock: row['Safety stock'] ? parseInt(row['Safety stock']) : 0,
          location: this.sanitizeInput(
            row['Inventory Location'] || row['location'],
          ),
          batchNo: this.sanitizeInput(row['Batch NO'] || row['batch_no']),
          expiryDate: this.sanitizeInput(
            row['Expiry date'] || row['expiry_date'],
          ),
          mfgDate: this.sanitizeInput(
            row['Manufacture Date'] || row['mfg_date'],
          ),
          supplier: this.sanitizeInput(row['Supplier'] || row['supplier']),
          brand: this.sanitizeInput(row['Brand'] || row['brand']),
          categoryId: categoryId,
          isActive,
        });
      } catch (error) {
        result.errors++;
        result.details.errorItems.push({
          row: rowNumber,
          name: row['Product Name'] || row['name'] || '-',
          error: error.message,
        });
      }
    }

    // 7. Bulk Insert
    if (validProductsToInsert.length > 0) {
      try {
        await this.db.transaction(async (tx) => {
          await tx.insert(schema.products).values(validProductsToInsert);
        });
        result.success += validProductsToInsert.length;
      } catch (error) {
        console.error('Batch Insert Error:', error);
        result.errors += validProductsToInsert.length;
        result.success = 0;
        result.details.errorItems.push({
          row: 0,
          name: 'Batch',
          error: `Batch Insert Failed: ${error.message}`,
        });
      }
    }

    return result;
  }

  // Backwards compatibility wrapper
  async bulkImport(csvBuffer: Buffer, tenantId: string) {
    const csvString = csvBuffer.toString('utf-8');
    const parsed = Papa.parse<Record<string, string>>(csvString, {
      header: true,
      skipEmptyLines: true,
      transformHeader: (header) => header.trim(),
    });
    return this.processBatch(parsed.data, tenantId);
  }
}
