import { useState } from 'react';
import { toast } from 'sonner';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../lib/api-client';
import Papa from 'papaparse';

export interface BulkUploadResult {
  success: number;
  skipped: number;
  errors: number;
  autoGeneratedSkus: number;
  details: {
    skippedItems: Array<{ sku: string; name: string; reason: string }>;
    errorItems: Array<{ row: number; name: string; error: string }>;
    autoSkus: Array<{ name: string; generatedSku: string }>;
  };
}

export function useBulkUpload() {
  const queryClient = useQueryClient();
  const [progress, setProgress] = useState(0);
  const [processedCount, setProcessedCount] = useState(0);
  const [totalCount, setTotalCount] = useState(0);

  const mutation = useMutation({
    mutationFn: async (file: File) => {
      // 1. Parse CSV
      return new Promise<BulkUploadResult>((resolve, reject) => {
        Papa.parse(file, {
          header: true,
          skipEmptyLines: true,
          complete: async (results) => {
            const rows = results.data as Record<string, any>[];
            const total = rows.length;
            setTotalCount(total);
            setProcessedCount(0);
            setProgress(0);

            const BATCH_SIZE = 50; // Smaller batches for better feedback
            const consolidatedResult: BulkUploadResult = {
              success: 0,
              skipped: 0,
              errors: 0,
              autoGeneratedSkus: 0,
              details: {
                skippedItems: [],
                errorItems: [],
                autoSkus: [],
              },
            };

            try {
              for (let i = 0; i < total; i += BATCH_SIZE) {
                const batch = rows.slice(i, i + BATCH_SIZE);

                // Send Batch
                const batchResult = await apiClient<BulkUploadResult>('/products/bulk-batch', {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({ items: batch }),
                });

                // Merge Results
                consolidatedResult.success += batchResult.success;
                consolidatedResult.skipped += batchResult.skipped;
                consolidatedResult.errors += batchResult.errors;
                consolidatedResult.autoGeneratedSkus += batchResult.autoGeneratedSkus;

                // Adjust row numbers for errors (since batch errors are 1-based relative to batch)
                const adjustedErrors = batchResult.details.errorItems.map((err) => ({
                  ...err,
                  row: i + err.row, // Offset by current index
                }));

                consolidatedResult.details.skippedItems.push(...batchResult.details.skippedItems);
                consolidatedResult.details.errorItems.push(...adjustedErrors);
                consolidatedResult.details.autoSkus.push(...batchResult.details.autoSkus);

                // Update Progress
                const currentProcessed = Math.min(i + BATCH_SIZE, total);
                setProcessedCount(currentProcessed);
                setProgress(Math.round((currentProcessed / total) * 100));
              }

              resolve(consolidatedResult);
            } catch (err) {
              reject(err);
            }
          },
          error: (err) => {
            reject(new Error(`CSV Parsing Failed: ${err.message}`));
          },
        });
      });
    },
    onSuccess: (data) => {
      toast.success(`Import complete: ${data.success} imported, ${data.errors} errors.`);
      queryClient.invalidateQueries({ queryKey: ['products'] });
    },
    onError: (error: Error) => {
      toast.error(`Import failed: ${error.message}`);
      setProgress(0);
    },
  });

  return {
    upload: mutation.mutate,
    isLoading: mutation.isPending,
    error: mutation.error,
    data: mutation.data,
    progress,
    processedCount,
    totalCount,
    reset: () => {
      mutation.reset();
      setProgress(0);
      setProcessedCount(0);
      setTotalCount(0);
    },
  };
}
