import { useState } from 'react';
import { toast } from 'sonner';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../lib/api-client';

export interface BulkUploadResult {
  success: number;
  skipped: number;
  errors: number;
  autoGeneratedSkus: number;
  details: {
    skippedItems: Array<{ sku: string; name: string; reason: string }>;
    errorItems: Array<{ row: number; name: string; error: string }>;
    autoSkus: Array<{ name: string; generatedSku: string }>;
  };
}

export function useBulkUpload() {
  const queryClient = useQueryClient();
  const [uploadProgress, setUploadProgress] = useState(0);

  const mutation = useMutation({
    mutationFn: async (file: File) => {
      const formData = new FormData();
      formData.append('file', file);

      // Simulating progress since fetch doesn't support upload progress natively easily
      // In a real app with axios/xhr we could track it.
      // For now, we'll fake it a bit or just show indeterminate state
      const interval = setInterval(() => {
        setUploadProgress((prev) => {
          if (prev >= 90) return prev;
          return prev + 10;
        });
      }, 100);

      try {
        const response = await apiClient<BulkUploadResult>('/products/bulk', {
          method: 'POST',
          body: formData,
          // Don't set Content-Type header, let browser set it with boundary
        });

        clearInterval(interval);
        setUploadProgress(100);
        return response;
      } catch (error) {
        clearInterval(interval);
        setUploadProgress(0);
        throw error;
      }
    },
    onSuccess: (data) => {
      toast.success(`Import complete: ${data.success} products imported.`);
      queryClient.invalidateQueries({ queryKey: ['products'] });
    },
    onError: (error: Error) => {
      toast.error(`Upload failed: ${error.message}`);
    },
  });

  return {
    upload: mutation.mutate,
    uploadAsync: mutation.mutateAsync,
    isLoading: mutation.isPending,
    error: mutation.error,
    data: mutation.data,
    progress: uploadProgress,
    reset: () => {
      mutation.reset();
      setUploadProgress(0);
    },
  };
}
