import { useState } from 'react';
import { BulkUploadResult } from '../hooks/use-bulk-upload';
import { CheckCircle, AlertTriangle, XCircle, Tag, ChevronDown, ChevronRight } from 'lucide-react';
import { cn } from '@repo/ui/lib/utils'; // Assuming utils endpoint exists or I will check later

export function ImportReport({ result }: { result: BulkUploadResult }) {
  const [expandedSection, setExpandedSection] = useState<'autoSkus' | 'skipped' | 'errors' | null>(
    null,
  );

  const toggleSection = (section: 'autoSkus' | 'skipped' | 'errors') => {
    if (expandedSection === section) {
      setExpandedSection(null);
    } else {
      setExpandedSection(section);
    }
  };

  return (
    <div className="w-full space-y-4 rounded-lg border bg-card text-card-foreground shadow-sm mt-6 p-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <h3 className="text-lg font-semibold mb-4">Import Summary</h3>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <div className="flex flex-col items-center justify-center p-4 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-100 dark:border-green-900/30">
          <CheckCircle className="h-8 w-8 text-green-600 mb-2" />
          <span className="text-2xl font-bold text-green-700 dark:text-green-400">
            {result.success}
          </span>
          <span className="text-sm text-green-600 dark:text-green-500">Imported</span>
        </div>

        <div className="flex flex-col items-center justify-center p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-100 dark:border-blue-900/30">
          <Tag className="h-8 w-8 text-blue-600 mb-2" />
          <span className="text-2xl font-bold text-blue-700 dark:text-blue-400">
            {result.autoGeneratedSkus}
          </span>
          <span className="text-sm text-blue-600 dark:text-blue-500">Auto SKUs</span>
        </div>

        <div className="flex flex-col items-center justify-center p-4 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg border border-yellow-100 dark:border-yellow-900/30">
          <AlertTriangle className="h-8 w-8 text-yellow-600 mb-2" />
          <span className="text-2xl font-bold text-yellow-700 dark:text-yellow-400">
            {result.skipped}
          </span>
          <span className="text-sm text-yellow-600 dark:text-yellow-500">Duplicates</span>
        </div>

        <div className="flex flex-col items-center justify-center p-4 bg-red-50 dark:bg-red-900/20 rounded-lg border border-red-100 dark:border-red-900/30">
          <XCircle className="h-8 w-8 text-red-600 mb-2" />
          <span className="text-2xl font-bold text-red-700 dark:text-red-400">{result.errors}</span>
          <span className="text-sm text-red-600 dark:text-red-500">Errors</span>
        </div>
      </div>

      <div className="space-y-2">
        {/* Auto SKUs Section */}
        {result.details.autoSkus.length > 0 && (
          <div className="border rounded-md overflow-hidden">
            <button
              onClick={() => toggleSection('autoSkus')}
              className="w-full flex items-center justify-between p-3 bg-muted/50 hover:bg-muted transition-colors text-sm font-medium"
            >
              <div className="flex items-center gap-2">
                <Tag className="h-4 w-4 text-blue-500" />
                <span>Auto-Generated SKUs ({result.details.autoSkus.length})</span>
              </div>
              {expandedSection === 'autoSkus' ? (
                <ChevronDown className="h-4 w-4" />
              ) : (
                <ChevronRight className="h-4 w-4" />
              )}
            </button>

            {expandedSection === 'autoSkus' && (
              <div className="p-0 overflow-x-auto max-h-60 overflow-y-auto">
                <table className="w-full text-sm text-left">
                  <thead className="text-xs text-muted-foreground bg-muted/30 uppercase">
                    <tr>
                      <th className="px-4 py-2">Product Name</th>
                      <th className="px-4 py-2">Generated SKU</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {result.details.autoSkus.map((item, i) => (
                      <tr key={i} className="hover:bg-muted/30">
                        <td className="px-4 py-2 font-medium">{item.name}</td>
                        <td className="px-4 py-2 font-mono text-xs">{item.generatedSku}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}

        {/* Skipped Items Section */}
        {result.details.skippedItems.length > 0 && (
          <div className="border rounded-md overflow-hidden">
            <button
              onClick={() => toggleSection('skipped')}
              className="w-full flex items-center justify-between p-3 bg-muted/50 hover:bg-muted transition-colors text-sm font-medium"
            >
              <div className="flex items-center gap-2">
                <AlertTriangle className="h-4 w-4 text-yellow-500" />
                <span>Skipped / Duplicates ({result.details.skippedItems.length})</span>
              </div>
              {expandedSection === 'skipped' ? (
                <ChevronDown className="h-4 w-4" />
              ) : (
                <ChevronRight className="h-4 w-4" />
              )}
            </button>

            {expandedSection === 'skipped' && (
              <div className="p-0 overflow-x-auto max-h-60 overflow-y-auto">
                <table className="w-full text-sm text-left">
                  <thead className="text-xs text-muted-foreground bg-muted/30 uppercase">
                    <tr>
                      <th className="px-4 py-2">SKU</th>
                      <th className="px-4 py-2">Product Name</th>
                      <th className="px-4 py-2">Reason</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {result.details.skippedItems.map((item, i) => (
                      <tr key={i} className="hover:bg-muted/30">
                        <td className="px-4 py-2 font-mono text-xs">{item.sku}</td>
                        <td className="px-4 py-2">{item.name}</td>
                        <td className="px-4 py-2 text-muted-foreground">{item.reason}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}

        {/* Errors Section */}
        {result.details.errorItems.length > 0 && (
          <div className="border rounded-md overflow-hidden">
            <button
              onClick={() => toggleSection('errors')}
              className="w-full flex items-center justify-between p-3 bg-muted/50 hover:bg-muted transition-colors text-sm font-medium"
            >
              <div className="flex items-center gap-2">
                <XCircle className="h-4 w-4 text-red-500" />
                <span>Errors ({result.details.errorItems.length})</span>
              </div>
              {expandedSection === 'errors' ? (
                <ChevronDown className="h-4 w-4" />
              ) : (
                <ChevronRight className="h-4 w-4" />
              )}
            </button>

            {expandedSection === 'errors' && (
              <div className="p-0 overflow-x-auto max-h-60 overflow-y-auto">
                <table className="w-full text-sm text-left">
                  <thead className="text-xs text-muted-foreground bg-muted/30 uppercase">
                    <tr>
                      <th className="px-4 py-2">Row</th>
                      <th className="px-4 py-2">Product Name</th>
                      <th className="px-4 py-2">Error</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {result.details.errorItems.map((item, i) => (
                      <tr key={i} className="hover:bg-muted/30">
                        <td className="px-4 py-2 font-mono text-xs">{item.row}</td>
                        <td className="px-4 py-2">{item.name}</td>
                        <td className="px-4 py-2 text-red-500">{item.error}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
