export interface BulkUploadResultDto {
  success: number;
  skipped: number;
  errors: number;
  autoGeneratedSkus: number;
  details: {
    skippedItems: Array<{ sku: string; name: string; reason: string }>;
    errorItems: Array<{ row: number; name: string; error: string }>;
    autoSkus: Array<{ name: string; generatedSku: string }>;
  };
}

export interface CsvProductRow {
  name: string;
  sku?: string;
  price: number;
  stock?: number;
  categoryId?: number;
  wholesalePrice?: number;
  taxRate?: number;
  uom?: string;
  reorderPoint?: number;
  safetyStock?: number;
  supplier?: string;
  brand?: string;
}
